### ISSUE TITLE
"Friday Night Livepeer" Regular Broadcast

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/project-management#12]
This project seeks to create a regular broadcast over Livepeer, in order to demonstrate the capabilities of the protocol as an alternative to other centralised live-streaming networks.

As a minimum set of requirements, we would need:

- **Permanent URL** - so that viewers know *WHERE* to go to view the content
- **Fixed time for broadcast** - so that viewers can know *WHEN* they will be able to view the content
- **Livepeer branded** - all content to be appropriately watermarked with Livepeer, to raise awareness of the project

Further iterations would seek to evolve the production with the following (in no particular order):

- **Monetisation mechanisms** - provide mechanisms for viewers to contribute financially to the creators either by tipping or pay-as-you-go. [A project proposal for this can be found here](https://github.com/livepeer/project-proposals/issues/4).
- **Concept Planning** - to create unique and original content, free of censorship
- **Stage Management / Direction** - to maintain engagement levels of content
- **Casting** - to source creators of high quality content to perform via this new channel
- **Publicity** - to raise awareness of the broadcast and for viewers to know when to tune in.
- **Packaging / Branding / Presentation** - define an engaging user interface for viewers to watch the content.

- **HD 1080p / UHD 4k** - seeking to broadcast the highest quality video possible
- **360° Streaming for VR** - broadcasting of 360° content for an immersive viewing experience
- **Stereo / Surround-sound Audio Design** - designing sound for an immersive audio experience

**Comment by rayj00** [comment]
For Fixed Time for Broadcast.... 
Have a subscriber database that sends notice of upcoming live stream. Broadcaster then shows pre-recorded video that says something like Stay Tuned...Live Video coming up in X minutes.   This will allow time for all interested viewers to logon the broadcast.

**Comment by chrishobcroft** [comment]
Great advice, thanks @rayj00
