### ISSUE TITLE
Community Call - Thursday, January 18 12:00pm EST, 18:00 CET

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#30]
# Livepeer Community Call 1/18/2018 - 12:00pm EST, 18:00 CET, 9:00am PST

## Participants and location

The community call is open to all. 

Participant Link: https://hangouts.google.com/hangouts/_/livepeer.org/chris?authuser=1
(if you're participating please go voice only unless presenting to conserve bandwidth, and mute when not speaking).

Live stream link to watch and follow along if not planning to actively participate: https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014

## Agenda

1. Testnet update - @dob 

2. Protocol testing/audit status - @yondonfu 

3. Protocol explorer demonstration - @jozanza 

4. Livepeer TV update and goals - @chrishobcroft 

## Roles

*Moderator*: @dob   
*Note taker*: @ericxtang   
*Streamer*: @jozanza 

Anybody should feel free to add agenda items or leave questions they'd like to discuss here in the issue. I'll keep the agenda up to date.

**Comment by dob** [comment]
My thought was that each call (whether once per week or every other week) we would rotate moderator, note taker, and streamer. I randomly picked @jozanza to be the streamer for the first one, but since he might be in transit, would @chrishobcroft be in a position to record and stream the call on Livepeer? If not, then we'll set up in the office to do it.

**Comment by jozanza** [comment]
I’m in office tomorrow, Doug.

**Comment by dob** [comment]
Updated the original issue with the livestream link (ingest node), and google hangout link for participants from the invite.

**Comment by dob** [comment]
@jozanza Cool, so good things to test for the streaming role include...

1. Make sure audio is captured from all participants on the call, and not just your own mic.
2. If you'd like to use a local node rather than the ingest node, which may result in higher quality video, let's update the stream address in this original note. (I can do when you provide it).
3. Let's record in addition to stream so we can upload to IPFS after.

**Comment by rayj00** [comment]
How do I attend as a viewer?

**Comment by rayj00** [comment]
Never mind...

**Comment by jozanza** [comment]
In about an hour, you can watch the conference live at https://media.livepeer.org/channels/0xe5f821b73b27c2be612307d4ef8082b2226c4202

🎉 🎉 🎉

**Comment by dob** [comment]
Final update to the stream URL, it will also be recorded, but it's available at http://livepeer.tv

**Comment by dob** [comment]
Notes from this call: https://forum.livepeer.org/t/livepeer-community-call-1-18-2018/132
