### ISSUE TITLE
Community Call - Thursday, Feb 22. 9AM PST, 12PM EST, 6PM CET

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#34]
# Livepeer Community Call 2/22/2018 - 12:00pm EST, 18:00 CET, 9:00am PST

## Participants and location

The community call is open to all. 

Participant Link: https://i.daily.co/dhal-bibimbap-baghrir
(if you're participating please go voice only unless presenting to conserve bandwidth, and mute when not speaking).

Live stream link to watch and follow along if not planning to actively participate: https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014

## Agenda

1. Airdrop Design Process.

2. Truebit integration update.

3. Launch plan

4. Questions, comments, open discussion.

## Roles

*Moderator*: @yondonfu      
*Note taker*: @chrishobcroft    
*Streamer*: @dob   

(Note, the roles rotate downward each week with @j0sh, @jozanza, and @ericxtang  on deck to fill the top of the queue). 

Anybody should feel free to add agenda items or leave questions they'd like to discuss here in the issue. I'll keep the agenda up to date.

**Comment by jozanza** [comment]
Here are the notes from the call: https://gist.github.com/jozanza/4301958282a36ddc3f1de62d46655345

**Comment by dob** [comment]
Great notes on the call from @jozanza: https://gist.github.com/jozanza/4301958282a36ddc3f1de62d46655345

**Comment by chrishobcroft** [comment]
Video uploaded on ipfs: https://ipfs.io/ipfs/QmTCfmEtAcVKYFpLiEyknVecCrBeNAR69fVhPP515AhB4K
