### ISSUE TITLE
LEPIP 1 - Attach Video Resolutions to Tasks During Planning / Daily Status

### ISSUE THREAD

**Issue by ericxtang** [livepeer/project-management#35]
This is the first LEPIP!  (Livepeer Engineering Process Improvement Proposal)

In the past, I have done agile processes where every engineering ticket is assigned points or t-shirt sizes.  This gives us some sense of velocity over time, and helps us think about capacity planning for weekly sprints.

I think our current engineering planning can benefit from such a scheme.  But since we are doing video stuff, why not use standard video resolutions?

The standard video resolutions are:
* 240p
* 360p
* 480p
* 720p
* 1080p

**Comment by dob** [comment]
On one hand...sure go for it. On the other hand...on the serious side, I actually think it's confusing. SD, HD, 4K might be easier to remember, pronounce, picture the association mentally, etc if we are dead set on using something video related. But 1, 2, 3, 4 or 1, 2, 4, 8 scales also seem to work pretty well for people :)

**Comment by j0sh** [comment]
At least with the *0p notation, numerical ordering is preserved :)

**Comment by ericxtang** [comment]
Ok.  Points taken.  Let's do 1,2,4,8?

**Comment by chrishobcroft** [comment]
Mm, for me this risks not being granular enough.

I worked with some agile evangelists a few years back who used:

> 0, ½, 1, 2, 3, 5, 8, 13, 21, 34, 100, ∞, ?

This allowed scope for people to class things as being e.g. "so easy why are we even talking" = 0, and also e.g. "this is verging on being impossible" = ∞ and also e.g. "I really have no idea how to estimate this" = ?.

Also, the "I really have no idea how to estimate this" allow so-called non-technical people to participate, to understand.

If you're going with something with memorable names (CGA, VGA, XVGA, HD, Full HD, 2k, 4k, 8k) , take a look at this image:

![image](https://user-images.githubusercontent.com/2212651/37425594-2ba53740-27c4-11e8-97a9-96f9846576d0.png)
