### ISSUE TITLE
Livepeer Hackathon - 5/9/2018

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#37]
Join the May Livepeer Community Hackathon: https://livepeercommunity.org/hackathon-may

**Open to all**
Participate at our NYC or Berlin workspaces, or join us remotely in [the Discord chat](https://discord.gg/bh9U23).

**Schedule**
1. Share ideas for hack projects here anytime.

2. 10:00am Eastern - video chat to share hack pitch ideas. Of course feel free to start hacking beforehand, but this is a good time to share ideas and team up! - https://zoom.us/j/856481657

3. 6:00pm Eastern - video chat to show off hacks. - https://zoom.us/j/856481657

**Preparation**
1. Check out [LivepeerJS](https://github.com/livepeer/livepeerjs)

2. Check out [Livepeer Developer Docs](livepeer.readthedocs.io)

3. If you want to develop on Ethereum, check out [truffle](http://truffleframework.com/) as a good tool for getting started. 

Feel free to post an ideas or ask any questions here.

**Comment by dob** [comment]
**Hack Ideas**

1. ENS integration for https://explorer.livepeer.org/transcoders - let transcoders choose their username and campaign URL, and display these on the explorer rather than just their ETH address.

2. Alerting service for transcoders - get notified if your transcoder missed a reward call, or changes their rates.

3. Status dashboard for transcoder node - the node locally stores all sorts of information about the current jobs being processed. It would be great to view some of this information.

4. ABS rendition selectors on media.livepeer.org player - choose between 1080p, 720p, 240p, etc.

5. Tip your broadcaster - ETH tip button on media.livepeer.org

6. Livepeer testnet on Ethermint.

**Comment by ericxtang** [comment]
My hack idea - video metrics tracking for Livepeer
1) For every new job creation, try to consume the video from the gateway, and keep track of the success rate.  
2) Parse the job/playlist and see if all of the transcoding profiles exist, and try to consume each video.
