### ISSUE TITLE
Livepeer Community Call - 8/16/18 - 12pm ET, 6pm CEST, 9am PT

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#42]
## Participants and location

The community call is open to all.

**Participant Link**: meet.google.com/wqt-putu-xwo

**Live stream link to watch and follow along if not planning to actively participate**: 

https://livepeer.tv

## Agenda

**Livepeer Wall of Shame!** .  
I found this to be a great exercise from Status. Take the time to identify the biggest items that we don't feel proud about as we represent Livepeer to the community: https://our.status.im/our-wall-of-shame/

Let's spend some time on the call building our own list of shame. And the resulting list will serve as a great target for personal OKR's or goals. If we can eliminate any item from the list, it's a huge victory.

**Tributary Release**
Let's do a quick check in on what we need to do to get the Tributary release out the door.

**Metrics Demo**
Eric and Ivan have been building out the metrics dashboard for Livepeer nodes in preparation of the Tributary release. They can give a demo of what's included.

## Roles

Moderator: @dob
Note taker: @ericxtang   
Streamer: @chrishobcroft  

Anybody should feel free to add agenda items or leave questions they'd like to discuss here in the issue. I'll keep the agenda up to date.

**Comment by joewest** [comment]
Random q: Are these recorded and published anywhere? I couldn't make the call, but really wanted to check out the Metrics Dashboard demo.

**Comment by dob** [comment]
@chrishobcroft did you happen to make a recording by any chance?

**Comment by j0sh** [comment]
Can poke around the actual dashboard here: http://metrics-rinkeby.livepeer.org/

Props to @darkdarkdragon for such a slick UI, and doing a lot of the work on the goclient metrics collection.

**Comment by dob** [comment]
And looks like I answered my own question. Recording appears to be here: https://www.youtube.com/watch?v=AsPbRUIakdA&feature=youtu.be&a=
