### ISSUE TITLE
Livepeer Community Call - 10/24/18 - 12pm ET, 6pm CET, 9am PT

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#44]
## Participants and location

The community call is open to all.

**Participant Link**: meet.google.com/wqt-putu-xwo

**Live stream link to watch and follow along if not planning to actively participate**: https://livepeer.tv

## Agenda

**Blockchain Video Unconference Recap** .  
Last week Livepeer hosted and participated in a great unconference with participants from many top video projects (centralized and decentralized), who were interested in exploring ways that video infrastructure can leverage decentralization to benefit transcoding, content delivery, content protection, storage, and more. We'll kick off with a recap and lessons learned from the conference.

**Devcon Update**
Livepeer will be at Devcon4 in Prague next week. We'll run through the topics we're interested in meeting with folks about, events we're presenting at, and what we hope to learn and accomplish.

**Open Q&A and Discussion**

Please add any questions or topics that you'd like to discuss in advance to this issue.

## Roles

Moderator: @RaffiSapire 
Note taker: @eladmallel    
Streamer: @dob   

Anybody should feel free to add agenda items or leave questions they'd like to discuss here in the issue. I'll keep the agenda up to date.

**Comment by eladmallel** [comment]
# 2018-10-25 Community Call Notes

Main topics we covered were:

1. Devcon4 Prep
2. SF Video Unconference Recap
3. Streamflow Update
4. New Team Members: Angie and Elad

## Devcon4 Prep

We shared the team's areas of interest for the week:

* Probabilistic micropayments
* Data availability problem
* zkSNARKs/STARKs
* Generalized mining
* Video enabling web3 infrastructure

Our team will attend several interesting events, such as:

* Status hackathon
* Swarm mini summit
* ETH Magicians Council of Prague
* Token engineering workshop
* App Awards
* Data availability breakout session
* Generalized mining meetup
* Probabilistic micropayments breakout session
* And more!

## SF Video Unconference Recap

This day was about connecting with blockchain video teams as well as non-blockchain teams (e.g. Peer5), to discuss how do we help decentralized and distributed video tech achieve its full potential?

The day consisted of lightning talks and breakout sessions, with topics crowdsourced from participants. [See detailed notes here](https://docs.google.com/document/d/1k17ZzH13Rx86KcXLz_LBjxwmCHnkf_7ylzBRHrvf2VA/edit#heading=h.3x56ecf5azkd).

Takeaways shared on the call:

* It's clear that enterprise video folks are showing increased interest in blockchain-based video solutions. It's a great idea for us to be having more conversations with them.
* Interesting and important question around incentivizing p2p participation, i.e. getting people to share their resources with the network. Seems there's consensus that solutions will be app/service-specific, and possibly implemented beyond the network protocol.
* This space is fragmented; people are working on small pieces of the stack. Users are looking for one-stop shops, and herein lies opportunity.
* We further validated that transcoding costs are a big issue for a lot of people. 
    * Many products only transcode their top videos, skipping the long tail.
* Video can be a key piece in getting mainstream adoption for blockchain.

## Streamflow Update

Doug updated on his plans to publish the Streamflow proposal in a few weeks and then setup multiple calls with transcoders to get detailed feedback. Target publish date: shortly after Devcon.
