### ISSUE TITLE
Livepeer diagram

### ISSUE THREAD

**Issue by ericxtang** [livepeer/project-management#50]
**Source**: John @ JWPlayer

**Feedback**: Would like to see a diagram of how video gets transcoded in the Livepeer network.

**Comment by rayj00** [comment]
I'd like to see something like this:
![image](https://user-images.githubusercontent.com/6609523/55180210-81076800-515f-11e9-95fe-717f8fce187e.png)

Obviously the broadcasting half is pretty simple.  It's the viewer side that confuses me.  So if you can
complete this,  that would be great.
