### ISSUE TITLE
FFMPEG on WASM

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#7]
To use Truebit for verification (and to support transcoding nodes in the browser?), it would be interesting or necessary to compile FFMPEG to Web Assembly. 

At this point this is more experimentation/research, but it would be great for someone to jump in and get started sharing what they learn about this process, and reporting on:

1. Ability to even do so.
2. What functionality restrictions do we end up with?
3. What is the resulting performance of a WASM FFMpeg encoding vs native?

**Comment by ericxtang** [comment]
Captured in research issue https://github.com/livepeer/research/issues/1
