### ISSUE TITLE
Facebook Alternative

### ISSUE THREAD

**Issue by rayj00** [livepeer/project-management#9]
I am sort of a political junkie.  I follow many Facebook popular conservative activists.  Facebook is giving them quite a hard time in what they post, especially their live broadcasts. They are being suspended from Facebook (thrown in "FB jail" is the term) because they may have said something that THEY (FB) consider to be not so Politically Correct.  Our Freedom of speech is eroding on a daily basis. 

It would be awesome if they had an alternative that could provide them with at least the abilities that Facebook offers and for free.

**Comment by chrishobcroft** [comment]
Great proposal - I fully support the freedom of speech and freedom of expression motivation.

Of all the abilities that Facebook offers, which is the priority to start with?

**Comment by rayj00** [comment]
Well, simple one person broadcasting live to many would be great for starters.
An update would be the ability for the single broadcaster to invite someone into his broadcast.

There are probably many more features that can be incorporated, but for now these would be awesome!

**Comment by rayj00** [comment]
After further thought on my suggestion above, this would not be a Livepeer issue, would it?  As long as I was using a broadcasting program (OBS for instance)  that allowed me to invite a guest into the broadcast, wouldn't this be transparent to Livepeer?   Or am I missing something?

**Comment by dob** [comment]
@rayj00 As far as inviting additional people into the broadcast, if you were using client software that allowed you to embed two video captures alongside one another like OBS, then this would occur outside of Livepeer, yes...as you would just be outputting one video into Livepeer.

If you wanted the Livepeer network itself to merge two streams into one output, this would be additional functionality that we'd have to bake into the protocol...which is probably unlikely for the time being. Better to think about ways to address this as the DApp level where you take two separate streams and just show them side by side in the player.

**Comment by chrishobcroft** [comment]
I use appear.in to broadcast a 2+ person video chat using OBS by sharing
the browser window.

While appear.in isn't a pure dApp (at least I don't think) it's a pretty
open platform with a Decentralized team and mindset.

I'm not sure of their censorship resistance though.

**Comment by rayj00** [comment]
The broadcasts I am interested in are 1 to Many….many being in the hundreds to mid-thousands of viewers.

 

Ray
